### ISSUE TITLE
[Maybe stupid question] Can I use this code for my own game?

### ISSUE THREAD

**Issue by lottev1991** [wolfderechter/DollMaker#1]
Hello,

See title. I'm mainly asking this because I noticed this repo doesn't have a license attached, and I have no intention to go against anyone's wishes. But I do like how this game works and I'd love to create my own dress up game with my own assets that basically works like this (with maybe some adjustments). I know this code is public but I still thought I'd ask due to a lack of license.

Thanks in advance!

**Comment by wolfderechter** [comment]
Hi, I've added the MIT license. So feel free to use the code however you want! Thanks for asking, and I'd love to see what you end up creating, good luck!

**Comment by lottev1991** [comment]
Thank you!
